### ISSUE TITLE
Missing config for alternate path

### ISSUE THREAD

**Issue by robhrt7** [nelsyeung/usemin-cli#2]
As far as I can see from docs/help, and trying similar approach from [gulp-usemin](https://github.com/zont/gulp-usemin), there's no way to define alternate path for assets. When  absolute paths to assets from `html` template are not matching actual routes, it's important to have an ability to define your own resolve directory.

Here's an example from gulp-usemin:

```
<!-- build:<pipelineId>(alternate search path) <path> -->
... HTML Markup, list of script / link tags.
<!-- endbuild -->
```

Would be nice to have an option in CLI to define resolve path.

**Comment by nelsyeung** [comment]
@operatino I've added this function to the dev branch. Do you mind testing it as well before I merge, as I've never actually used this functionality before in the real world?
