### ISSUE TITLE
Config file not respected

### ISSUE THREAD

**Issue by mbarzeev** [nelsyeung/usemin-cli#5]
Hi,
I'm trying to add configuration to the uglifyjs, but it doesn't seem to work.
Here is the content of my file.
BTW is that the configuration option? I've looked over the uglifyjs repo and this is the best I could find...

```
module.exports = {
        outSourceMap: "out.js.map"
    },
    cleancss: {
        // ... CleanCSS API options
    },
    htmlminifier: {
        // ... HTML minifier API options
    }
}
```

Am I missing something?
Thanks for the help

**Comment by nelsyeung** [comment]
Have you tried the following?
```js
module.exports = {
    uglifyjs: {
        outSourceMap: 'out.js.map'
    },
}
```

**Comment by mbarzeev** [comment]
Sorry - my bad. Didn't look in the right place.
Thanks!

**Comment by mbarzeev** [comment]
And again... I can't seem to find the generated file... I see that the output minified file contains the 
`//# sourceMappingURL=out.js.map`
but it has nothing to map to. there is no out.js.map file.
I'm obviously missing something here... appriciate the help.

**Comment by nelsyeung** [comment]
I've just published v0.4.2 with this fix. Please check again.

Sorry about this, I myself don't use this tool enough nowadays to notice some api changes within uglifyjs.

**Comment by mbarzeev** [comment]
Thanks.
Mind if I ask what tool are you using instead? ;)

**Comment by nelsyeung** [comment]
Since I kinda like working with ES6 as my default, so I started to use Webpack for most of my projects. I have a little web template for small websites which I use now: [es6-web-template](https://github.com/nelsyeung/es6-web-template) (it's not really complete yet as it doesn't copy assets).

**Comment by mbarzeev** [comment]
I see...
Thanks.
