### ISSUE TITLE
list blocks to stdout

### ISSUE THREAD

**Issue by joh-klein** [nelsyeung/usemin-cli#6]
What do you think of an option [like this](https://github.com/jhicken/grunt-usemin-list), so just output to stdout a json with the files so that they can be used elsewhere?

**Comment by nelsyeung** [comment]
The API version of this already has this function: [nelsyeung/usemin](https://github.com/nelsyeung/usemin#usemingetblocksfilepath-content-removelivereload), where it can return the relevant objects. I guess you just want me to incorporate it into this CLI tool where it writes it into a JSON file? Although I would recommend maybe just using the API if you want more manipulation.

**Comment by joh-klein** [comment]
Yeah, I saw that usemin api returns these things. And I was actually thinking about using it. But the cli would be enough. And maybe others (that have to support legacy projects and can't use webpack just yet) appreciate this as an option as well.

**Comment by nelsyeung** [comment]
So currently I'm thinking of adding a `--listblocks` argument with the options `stdout` and `filename.json` which will write to stdout and a json file, respectively, from what the `getBlocks` function returns. Is this what you are thinking?

**Comment by joh-klein** [comment]
Sounds perfect!

**Comment by nelsyeung** [comment]
Before I publish, do you mind playing around with the update I've added.
You can install from GitHub using:
```sh
git clone https://github.com/nelsyeung/usemin-cli.git
cd usemin-cli
npm link
```

**Comment by joh-klein** [comment]
Nice. I just tried it. Works pretty much as expected. Thanks a lot! I would have thought that --listblocks without an argument would print to stdout, but its fine either way.

**Comment by nelsyeung** [comment]
I've made it default to stdout and the new version is now published. :)
